Adding multi os builds

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,11 +25,31 @@ jobs:
           key: pkg-cache-{{ checksum "Gopkg.lock" }}
           paths:
             - "/go/src/github.com/garden-io/garden/vendor"
-      - run: cd garden-cli && go build -v -o garden
+      - run: cd garden-cli
 
+      - run:
+          name: Build darwin/amd64
+          command: |
+            package_name="garden"
+            platforms=("windows/amd64" "windows/386" "darwin/amd64")
+            for platform in "${platforms[@]}"
+            do
+                platform_split=(${platform//\// })
+                GOOS=${platform_split[0]}
+                GOARCH=${platform_split[1]}
+                output_name=$package_name'-'$GOOS'-'$GOARCH
+                if [ $GOOS = "windows" ]; then
+                    output_name+='.exe'
+                fi
+
+                env GOOS=$GOOS GOARCH=$GOARCH go build -o build/$output_name
+                if [ $? -ne 0 ]; then
+                    echo 'An error has occurred! Aborting the script execution...'
+                    exit 1
+                fi
+            done
       - store_artifacts:
-          path: garden-cli/garden
-          destination: garden
+          path: build/*
 
 
 #   build:
