WIP tests for functions

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,16 +3,43 @@
 # Check https://circleci.com/docs/2.0/language-javascript/ for more details
 #
 version: 2
-jobs:
-  build-go:
+
+## Configuration here can be shared across jobs
+.references:
+  go-config: &go-config
     docker:
       - image: circleci/golang:1.10
     working_directory: /go/src/github.com/garden-io/garden
+  go-builder: &go-builder
+    steps:
+      - checkout
+      - restore_cache:
+        keys:
+          - pkg-cache-{{ checksum "Gopkg.lock" }}
+      - run:
+        name: Install dep
+        command: |
+          if [ ! -d /go/src/github.com/garden-io/garden/vendor ]; then
+              curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep
+              chmod +x /go/bin/dep
+              /go/bin/dep ensure
+          fi
+      - save_cache:
+        key: pkg-cache-{{ checksum "Gopkg.lock" }}
+        paths:
+          - "/go/src/github.com/garden-io/garden/vendor"
+      - run: cd garden-cli
+
+# Jobs definitions
+jobs:
+  test-cli:
+    <<: *go-config
     steps:
       - checkout
       - restore_cache:
           keys:
             - pkg-cache-{{ checksum "Gopkg.lock" }}
+      - run: go get -u github.com/jstemmer/go-junit-report
       - run:
           name: Install dep
           command: |
@@ -25,32 +52,12 @@ jobs:
           key: pkg-cache-{{ checksum "Gopkg.lock" }}
           paths:
             - "/go/src/github.com/garden-io/garden/vendor"
-      - run:
-          name: Build All
-          command: |
-            cd garden-cli
-            package_name="garden"
-            platforms=("windows/amd64" "windows/386" "darwin/amd64" "linux/amd64")
-            for platform in "${platforms[@]}"
-            do
-                platform_split=(${platform//\// })
-                GOOS=${platform_split[0]}
-                GOARCH=${platform_split[1]}
-                output_name=$package_name'-'$GOOS'-'$GOARCH
-                if [ $GOOS = "windows" ]; then
-                    output_name+='.exe'
-                fi
-
-                env GOOS=$GOOS GOARCH=$GOARCH go build -o build/$output_name
-                if [ $? -ne 0 ]; then
-                    echo 'An error has occurred! Aborting the script execution...'
-                    exit 1
-                fi
-            done
+      - run: cd garden-cli && go test -v 2>&1 | go-junit-report > /tmp/report.xml
       - store_artifacts:
-          path: garden-cli/build
-          destination: /downloads
-  test-node:
+          path: /tmp/report.xml
+      - store_test_results: # Upload test results for display in Test Summary
+          path: /tmp/
+  test-service:
     docker:
       - image: circleci/node:10
     steps:
@@ -94,10 +101,54 @@ jobs:
       - run:
           name: test
           command: npm run ci-test
+  build-cli:
+    <<: *go-config
+    steps:
+      - checkout
+      - restore_cache:
+        keys:
+          - pkg-cache-{{ checksum "Gopkg.lock" }}
+      - run:
+        name: Install dep
+        command: |
+          if [ ! -d /go/src/github.com/garden-io/garden/vendor ]; then
+              curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep
+              chmod +x /go/bin/dep
+              /go/bin/dep ensure
+          fi
+      - save_cache:
+        key: pkg-cache-{{ checksum "Gopkg.lock" }}
+        paths:
+          - "/go/src/github.com/garden-io/garden/vendor"
+      - run:
+          name: Build All
+          command: |
+            cd garden-cli
+            package_name="garden"
+            platforms=("windows/amd64" "windows/386" "darwin/amd64" "linux/amd64")
+            for platform in "${platforms[@]}"
+            do
+                platform_split=(${platform//\// })
+                GOOS=${platform_split[0]}
+                GOARCH=${platform_split[1]}
+                output_name=$package_name'-'$GOOS'-'$GOARCH
+                if [ $GOOS = "windows" ]; then
+                    output_name+='.exe'
+                fi
+
+                env GOOS=$GOOS GOARCH=$GOARCH go build -o build/$output_name
+                if [ $? -ne 0 ]; then
+                    echo 'An error has occurred! Aborting the script execution...'
+                    exit 1
+                fi
+            done
+      - store_artifacts:
+          path: garden-cli/build
+          destination: /downloads
 
 workflows:
  version: 2
  all-tests:
    jobs:
-     - build-go
-     - test-node
+     - test-cli
+     #- test-service
